version: '3.7'

services:
  n8n:
    image: n8nio/n8n:1.59.0
    container_name: n8n
    ports:
      - 5678:5678
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      - TZ=Europe/Moscow
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=1234
    restart: unless-stopped
